name: Jira Sync
on:
  issues:
    types: [opened, labeled, unlabeled]
  issue_comment:
    types: [created]
jobs:
  sync:
    name: Sync Items
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: mheap/github-action-issue-to-jira@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          jiraHost: https://dsdmoj.atlassian.net/
          jiraUsername: aaron.robinson1@justice.gov.uk
          jiraPassword: ${{ secrets.JIRA_API_TOKEN_AR }}
          project: TC
          assignee: default_assignee